import type { PowerUpDefinition } from './types/powerup.js';

export const POWERUP_CATALOG: PowerUpDefinition[] = [
  // Self-beneficial
  {
    id: 'steady_aim',
    name: 'Steady Aim',
    description: 'Removes aim wobble for your next shot',
    target: 'self',
    icon: '🎯',
    color: '#4CAF50',
  },
  {
    id: 'power_shot',
    name: 'Power Shot',
    description: '1.5x power on your next putt',
    target: 'self',
    icon: '💪',
    color: '#FF9800',
  },
  {
    id: 'magnet',
    name: 'Magnet',
    description: 'Ball is attracted toward the hole for 5 seconds',
    target: 'self',
    duration: 5,
    icon: '🧲',
    color: '#F44336',
  },
  {
    id: 'rewind',
    name: 'Rewind',
    description: 'Undo your last stroke and restore ball position',
    target: 'self',
    icon: '⏪',
    color: '#9C27B0',
  },
  {
    id: 'ghost_ball',
    name: 'Ghost Ball',
    description: 'Pass through walls for 3 seconds',
    target: 'self',
    duration: 3,
    icon: '👻',
    color: '#E0E0E0',
  },
  {
    id: 'teleport',
    name: 'Teleport',
    description: 'Move your ball to any point on the course',
    target: 'self',
    icon: '✨',
    color: '#00BCD4',
  },

  // Opponent-targeting
  {
    id: 'super_size',
    name: 'Super Size',
    description: "Enlarges opponents' balls so they can't fit in the hole",
    target: 'all_opponents',
    duration: 10,
    icon: '🔴',
    color: '#E91E63',
  },
  {
    id: 'fun_size',
    name: 'Fun Size',
    description: "Shrinks opponents' balls making them harder to control",
    target: 'all_opponents',
    duration: 10,
    icon: '🔵',
    color: '#3F51B5',
  },
  {
    id: 'ice_rink',
    name: 'Ice Rink',
    description: 'Makes the floor slippery for opponents',
    target: 'all_opponents',
    duration: 8,
    icon: '🧊',
    color: '#B3E5FC',
  },
  {
    id: 'reversiball',
    name: 'Reversiball',
    description: "Reverses opponents' aim direction for their next putt",
    target: 'all_opponents',
    icon: '🔄',
    color: '#FF5722',
  },
  {
    id: 'twisted_aim',
    name: 'Twisted Aim',
    description: "Makes opponents' aim arrow spin continuously",
    target: 'all_opponents',
    duration: 8,
    icon: '🌀',
    color: '#795548',
  },
  {
    id: 'zanyball',
    name: 'Zanyball',
    description: "Doubles opponents' ball speed uncontrollably",
    target: 'all_opponents',
    duration: 5,
    icon: '⚡',
    color: '#FFEB3B',
  },
  {
    id: 'steal',
    name: 'Steal',
    description: "Take a random power-up from a specific opponent",
    target: 'opponent',
    icon: '🦝',
    color: '#607D8B',
  },
  {
    id: 'fog',
    name: 'Fog',
    description: 'Reduces visibility for opponents',
    target: 'all_opponents',
    duration: 8,
    icon: '🌫️',
    color: '#B0BEC5',
  },
  {
    id: 'earthquake',
    name: 'Earthquake',
    description: 'Shakes the screen for opponents',
    target: 'all_opponents',
    duration: 5,
    icon: '🌍',
    color: '#8D6E63',
  },
];

export function getPowerUpById(id: string): PowerUpDefinition | undefined {
  return POWERUP_CATALOG.find((p) => p.id === id);
}
